services:
  ros2_waffle:
    container_name: ros2-waffle
    build: ./
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - type: bind
        source: ${ROS_PROJECT_PATH}
        target: /home/student/ros2_ws/src
      - ros2_workspace:/home/student/ros2_ws
    environment:
      - DISPLAY=$DISPLAY
    network_mode: host # Enable COMMS to a real waffle?
    networks:
      - x11
    stdin_open: true
    tty: true
    privileged: true
networks:
  x11:

volumes:
  ros2_workspace:
