services:
  ros2_waffle:
    container_name: ros2-waffle
    build: ./
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - type: bind
        source: ${ROS_PROJECT_PATH}
        target: /home/student/ros2_ws/src
      - ros2_workspace:/home/student/ros2_ws
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - x11
    stdin_open: true
    tty: true
    privileged: true
networks:
  x11:

volumes:
  ros2_workspace:
