#!/usr/bin/env bash

# Diamond Tools for WSL

SRC_DIR="/home/diamond/ros2-waffle"

update_src() {
  if id -nG "${USER}" | grep -qw "sudo"; then
    echo "Checking for updates..."
    cd $SRC_DIR && git pull --quiet
  else
    echo "Non-admin user, skipping updates..."
  fi
}

getx() {
  update_src

  SCRIPT=$1
  COPY_SCRIPT="$SCRIPT-$(date +'%Y%m%d%H%M%S')"
  echo "[INFO] Obtaining '${SCRIPT}.sh' script..."
  
  DIAMOND_TOOLS_LOCAL_DIR=/home/diamond/diamond_tools_local/
  mkdir -p ${DIAMOND_TOOLS_LOCAL_DIR}
  
  cd ${DIAMOND_TOOLS_LOCAL_DIR}
  cp ${SRC_DIR}/wsl/diamond_tools/${SCRIPT}.sh ./${COPY_SCRIPT}.sh
  
  echo "[INFO] Executing..."
  chmod +x ${COPY_SCRIPT}.sh && ./${COPY_SCRIPT}.sh
}

if [[ $# -eq 0 ]]; then
  echo "No input command provided. Exiting."
  exit 1
else
  COMMAND=$1
fi

case $COMMAND in 
  update)
    getx ${COMMAND}
    ;;
  *)
    echo "Not a valid input."
    exit 1
    ;;
esac
